### ISSUE TITLE
context example

### ISSUE THREAD

**Issue by herringtown** [alterway/component-workflow#1]
Hi there, wondering if you could flesh out the provided usage example with some context scenarios? I'm a little fuzzy on how they are to be implemented and it would nice to see some business rule examples that allow the workflow to advance (isSatisfiedBy) or not.....thanks!

**Comment by trompette** [comment]
Hi @herringtown!

I will try to find some time to write better documentation. I'm not sure when, though...

Cheers!

**Comment by herringtown** [comment]
Thanks @trompette! No rush. This is all very well conceived, btw -- excellent work!

**Comment by trompette** [comment]
@herringtown, see #3 for a work in progress. I would like your input on this.
